// <auto-generated />
using System;
using ControleGlicemiaDiario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleGlicemiaDiario.Migrations
{
    [DbContext(typeof(GlicemiaContext))]
    [Migration("20230522035744_Inicial - Cria BD e Tabela Glicemia")]
    partial class InicialCriaBDeTabelaGlicemia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleGlicemiaDiario.Models.Glicemia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoseAjuste")
                        .HasColumnType("int");

                    b.Property<int?>("DoseRegulat")
                        .HasColumnType("int");

                    b.Property<int>("GlicemiaMedida")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GLICEMIAS");
                });
#pragma warning restore 612, 618
        }
    }
}
