// <auto-generated />
using System;
using ControleGlicemiaDiario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleGlicemiaDiario.Migrations
{
    [DbContext(typeof(GlicemiaContext))]
    partial class GlicemiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleGlicemiaDiario.Models.Glicemia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraMedicao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoseAjuste")
                        .HasColumnType("int");

                    b.Property<int?>("DoseRegular")
                        .HasColumnType("int");

                    b.Property<int>("GlicemiaMedida")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GLICEMIAS");
                });

            modelBuilder.Entity("ControleGlicemiaDiario.ViewModels.GlicemiaVM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataHoraAplicação")
                        .HasMaxLength(14)
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraMedicao")
                        .HasMaxLength(14)
                        .HasColumnType("datetime2");

                    b.Property<int?>("DoseAjuste")
                        .HasColumnType("int");

                    b.Property<int?>("DoseRegular")
                        .HasColumnType("int");

                    b.Property<int>("GlicemiaMedida")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.ToTable("GlicemiaVM");
                });
#pragma warning restore 612, 618
        }
    }
}
